language: node_js
node_js:
  "11"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - yarn install
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
